services:
  redis:
    image: redis:latest
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
      - TZ=Europe/Moscow
    restart: always
    networks:
      - telegram_lesson_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
      - TZ=Europe/Moscow
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    restart: always
    networks:
      - telegram_lesson_network
